
    # disable pretty URLS and keep `index.html` & trailing `.html` file references in paths
  prettyURLs = false


  [build]
  publish = "dist/app"

  [[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self';"
